####  Exploring Attention Mechanisms

In [31]:
import torch
import numpy as np

inputs = torch.tensor([
  [0.46, 0.86, 0.83],
  [0.36, 0.74, 0.78],
  [0.37, 0.94, 0.63],
  [0.64, 0.52, 0.94],
  [0.96, 0.84, 0.31],
  [0.53, 0.74, 0.18],
])

query_token = inputs[0]
#print(inputs.shape)

## This vector holds the dot product results between each embedding vector
## for each token in our context and the embedding vector of our query token,
## our query token being the token we're using to try and predict what word w
## should come next.
attention_score_vector = torch.empty(inputs.shape[0])
#print("Attention", attention_result_vector)

for index, tensor in enumerate(inputs):
  attention_score_vector[index] = torch.dot(query_token, inputs[index])

print(torch.round(attention_score_vector, decimals=4))

tensor([1.6401, 1.4494, 1.5015, 1.5218, 1.4213, 1.0296])


#### Now, we wish to normalize the attention score vector
##### Helps with optimization - to work with smaller numbers.

In [32]:
attention_score_vector_normalized = attention_score_vector/torch.sum(attention_score_vector)
print(attention_score_vector)
print(attention_score_vector_normalized)

tensor([1.6401, 1.4494, 1.5015, 1.5218, 1.4213, 1.0296])
tensor([0.1915, 0.1692, 0.1753, 0.1777, 0.1660, 0.1202])
